apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-dpl
  labels:
    app: cdn
spec:
  replicas: 5 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  selector:
    matchLabels:
      app: cdn
  template:
    metadata:
      labels:
        app: cdn
    spec:
      containers:
      - name: cdn-slave
        image: entty/cloud_project:latest
        imagePullPolicy: Always
        env:
        volumeMounts:
        - mountPath: /var/www/html/mounted
          name: test-volume
      volumes:
      - name: test-volume
        persistentVolumeClaim:
          claimName: cdn-master-pvc        
