apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdn-master-pvc 
  labels:
    app: cdn
spec:
  accessModes:
    # only AccessModes [ReadWriteOnce] are supported on gp2-volumes in ebs
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
