## LoadBalancer should make us visible on LAN-IP
apiVersion: v1
kind: Service
metadata:
  name: cdn-svc
  labels:
    app: cdn
spec:
  selector:
    app: cdn
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetport: 8080
    

### Using Service type NodePort --> endpoint only available inside cluster or via "kubectl proxy"
# apiVersion: v1
# kind: Service
# metadata:
  # name: cdn-svc
  # namespace: cdn-ns
# spec:
  # type: NodePort
  # selector:
    # app: cdn-overmind
  # ports:
  # - port: 80
    # targetPort: 80
    # nodePort: 30080
