## LoadBalancer should make us visible on LAN-IP
apiVersion: v1
kind: Service
metadata:
  name: cdn-svc
  namespace: modules
spec:
  ports:
    - port: 80
  type: LoadBalancer
  selector:
    app: cdn-overmind
    

### Using Service type NodePort --> endpoint only available inside cluster or via "kubectl proxy"
# apiVersion: v1
# kind: Service
# metadata:
  # name: cdn-svc
  # namespace: cdn-ns
# spec:
  # type: NodePort
  # selector:
    # app: cdn-overmind
  # ports:
  # - port: 80
    # targetPort: 80
    # nodePort: 30080
