apiVersion: v1
kind: Service
metadata:
  name: cdn-master-svc
  labels:
    app: cdn
spec:
  type: NodePort
  selector:
    app: cdn
    tier: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    #clusterIP: None
  # How to define multiple ports? need more services?
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: master-pv-claim
    labels:
      app: cdn
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-dpl
  labels:
    app: cdn
    tier: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdn
  template:
    metadata:
      labels:
        app: cdn
        tier: apache
    spec:
      containers:
      - name: cdn-master
        image: entty/cloud_project:latest
        env:
          - name: CDN_ROLE 
            value: "MASTER"
          - name: SLAVE_IP
            value: localhost
        volumeMounts:
        - name: master-filestorage
          mountPath: /var/share
      volumes:
          # toDo: switch to getting storage config from different configMaps for development and production. can't use ebs volume on local nodes.
      - name: master-filestorage
        persistentVolumeClaim:
          claimName: master-pv-claim
            # This AWS EBS volume must already exist.
            #awsElasticBlockStore:
            #  volumeID: vol-021376eb4be8f0714 #vol-09cf1bb1375ee6749 #"vol-021376eb4be8f0714" must exist, zone must match instance zone
            #  fsType: ext4
---
#apiVersion: batch/v1beta1
#kind: CronJob
#metadata:
#  name: syncer
#spec:
#  schedule: "* */10 * * *"
#  jobTemplate:
#    spec:
#      template:
#        spec:
#          containers:
#          - name: rsync
#            image: eeacms/rsync
#            imagePullPolicy: IfNotPresent
#            args:
#            - --help #rm -i -v /data:/share instrumentisto/rsync-ssh rsync -avz ${SLAVE_IP}:/share /mnt/
#          restartPolicy: Never
#
