apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdn
  template:
    metadata:
      labels:
        app: cdn
    spec:
      containers:
      - name: cdn-master
        image: entty/cloud_project:latest
        env:
          - name: CDN_ROLE 
            value: "MASTER"
        volumeMounts:
          - mountPath: /var/www/html/test123
            name: test-volume
      volumes:
          # toDo: switch to getting storage config from different configMaps for development and production. can't use ebs volume on local nodes.
          - name: test-volume
            # This AWS EBS volume must already exist.
            awsElasticBlockStore:
              volumeID: vol-09cf1bb1375ee6749 #"vol-021376eb4be8f0714" must exist, zone must match instance zone
              fsType: ext4


--- 
## LoadBalancer should make us visible on LAN-IP
apiVersion: v1
kind: Service
metadata:
  name: cdn-svc
spec:
  ports:
    - port: 80
  type: LoadBalancer
  selector:
    app: cdn
### Using Service type NodePort --> only available inside cluster or via "kubectl proxy"
# apiVersion: v1
# kind: Service
# metadata:
  # name: cdn-svc
  # namespace: cdn-ns
# spec:
  # type: NodePort
  # selector:
    # app: cdn-overmind
  # ports:
  # - port: 80
    # targetPort: 80
    # nodePort: 30080
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* */10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - date; echo Hello from cluster node $HOSTNAME;
          restartPolicy: OnFailure

