apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdn-dpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdn
  template:
    metadata:
      labels:
        app: cdn
    spec:
      containers:
      - name: cdn-master
        image: entty/cloud_project:latest
        env:
          - name: CDN_ROLE 
            value: "MASTER"
          - name: SLAVE_IP
            value: localhost
        volumeMounts:
        - name: master-filestorage
          mountPath: /var/share
      volumes:
          # toDo: switch to getting storage config from different configMaps for development and production. can't use ebs volume on local nodes.
      - name: master-filestorage
        persistentVolumeClaim:
          claimName: master-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: master-pv-claim
    labels:
      app: cdn
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
--- 
apiVersion: v1
kind: Service
metadata:
  name: cdn-svc
spec:
  ports:
    - name: frontendport
      port: 80
    - name: backendport
      port: 8008
  type: LoadBalancer
  selector:
    app: cdn
### Using Service type NodePort --> only available inside cluster or via "kubectl proxy"
# apiVersion: v1
# kind: Service
# metadata:
  # name: cdn-svc
  # namespace: cdn-ns
# spec:
  # type: NodePort
  # selector:
    # app: cdn-overmind
  # ports:
  # - port: 80
    # targetPort: 80
    # nodePort: 30080
---
# apiVersion: batch/v1beta1
# kind: CronJob
# metadata:
  # name: hello
# spec:
  # schedule: "* */10 * * *"
  # jobTemplate:
    # spec:
      # template:
        # spec:
          # containers:
          # - name: hello
            # image: busybox
            # imagePullPolicy: IfNotPresent
            # args:
            # - /bin/sh
            # - -c
            # - date; echo Hello from cluster node $HOSTNAME;
          # restartPolicy: OnFailure

